### PR TITLE
Fix SuccessStory Plugin Crashes, Auth Issues

### LINKED ISSUE #609: "Response status code does not indicate success: 404 (Not Found)" error on Playnite startup
**Describe the bug**
I get this error at every Playnite startup. Clicking on it just asks if I want to create a log file, which I've attached below.

**To Reproduce**
Start Playnite

**Expected behavior**
No errors to pop up.

**Screenshots**

Image

**Extensions log**

[SuccessStory_2025-05-16.zip](https://github.com/user-attachments/files/20259175/SuccessStory_2025-05-16.zip)

[extensions.log](https://github.com/user-attachments/files/20259176/extensions.log)

### LINKED ISSUE #661: Playnite frozing after importing xbox360 achivements
**Describe the bug**
The second I press Import from exophase 360 achivements, playnite frozes

**To Reproduce**
Importing exophase 360 achivments

**Expected behavior**
The tonedown playnite dose to show it refreshing but it gets stock

**Screenshots**
Image

**Extensions log**
[extensions.log](https://github.com/user-attachments/files/24272537/extensions.log)

### LINKED ISSUE #663: RPCS3 achievements fails to import if there is no unlock date or time
**Describe the bug**
SuccessStory finds the Trophy Path and finds all the achievements, but fails to import. Game in question is Drakengard 3

**To Reproduce**
Attempt to refresh data. Wait for the process to complete. Error notification pops up in playnite. 

**Expected behavior**
imports achievements even if there is no date or time

**Extensions log**
[extensions.log](https://github.com/user-attachments/files/24274169/extensions.log)

### LINKED ISSUE #664: Bug about Xbox Sync, Sorting, and Integration
Hello, Thank you for the recent update. I’ve encountered a few issues and have attached my log files for review.

1. Xbox sync is acting a bit weird. While Steam works perfectly, the Xbox side is hit-or-miss. It works fine for 33 Immortals, but for games like Silksong or Nine Sols, it fails to load anything. Looking at the logs, it seems like there are some missing JSON files or "FileNotFound" errors specifically for those games.

2. The achievement sorting seems stuck. I have it set to "Unlocked Time" so I can see my recent progress, but it keeps defaulting to alphabetical order (A-Z) no matter what I do.

3. EA integration isn't really doing anything. Even though my account is linked, the updates don't seem to trigger. I noticed a "NullReferenceException" in the logs during the EA game info check, which might be why it's failing.

4. I'm stuck in an Exophase login loop. Whenever I click the checkmark to verify, it just loads for a second and then asks me to click it again. The logs mention that there are "no stored cookies" or "no token saved" for Exophase, so it feels like the session isn't being recorded.

I’ve attached the full logs so you can take a closer look at what’s happening under the hood. Thanks again for all the hard work you put into this!

[playnite.log](https://github.com/user-attachments/files/24275871/playnite.log)
[extensions.log](https://github.com/user-attachments/files/24275870/extensions.log)

and Epic Games sync errors: On top of the Xbox issues, I've noticed that Epic Games is also throwing errors and failing to sync properly now.

[extensions.log](https://github.com/user-attachments/files/24275900/extensions.log)
[playnite.log](https://github.com/user-attachments/files/24275899/playnite.log)

### LINKED ISSUE #665: Cannot add manual achievements anymore
So, I already had this issue: https://github.com/Lacro59/playnite-successstory-plugin/issues/640

In the meantime, for RA games, I used to just add achievements manually from Exophase (by the way if we could have some Unlock All/Lock All option so it's faster to check them/uncheck only those not earned).

But, I just updated and now cannot even add manual achievements to a manually added game anymore...

### LINKED ISSUE #666: epic games ach wont be added
**Describe the bug**
as the title says when i try to refresh ach for epic games  i just get the error in the screenshot 

**To Reproduce**
adding an epic game using the update game library function on playnite then right clicking on the game and refreshing 

**Screenshots**

Image

**Extensions log**

[extensions.00011.log](https://github.com/user-attachments/files/24278868/extensions.00011.log)
[extensions.00012.log](https://github.com/user-attachments/files/24278869/extensions.00012.log)
[extensions.log](https://github.com/user-attachments/files/24278870/extensions.log)

### LINKED ISSUE #667: Object reference not set to an instance of an object error
**Describe the bug**
When trying to refresh game data, I get the error in the title. This happens with all platforms except Steam. When downloading the data it does look like it's pulling data but once it's complete nothing shows in the SuccessStory tab, even when closing/re-opening Playnite. I have tried with psn, gog and retroachievements

**To Reproduce**
Open Playnite
Go to Menu > Extensions > SuccessStory > Download data
Click download

**Expected behavior**
Should show achievement data for various platforms

**Screenshots**

**Extensions log**
[extensions.log](https://github.com/user-attachments/files/24330512/extensions.log)

### LINKED ISSUE #668: GOG can't authenticate
**Describe the bug**
GOG can't authenticate either with login method or account ID

**To Reproduce**
Open Playnite
Press F9 to open plugin manager
Go to Extension Settings > Generic > SuccessStory
Go to Libraries tab
Drop down on GOG
In account Configuration, tick "is private"
Click authenticate 
Sign into GOG account (window stays open after you sign in)
close out of the window
Refresh Data on GOG game
Go back to GOOG SuccessStory settings
untick "is private"
Paste account ID
close out of the window
Refresh Data on GOG game

**Expected behavior**
Should authenticate using either login or User ID

**Screenshots**

Image

**Extensions log**
[extensions.log](https://github.com/user-attachments/files/24330647/extensions.log)

### LINKED ISSUE #670: Object reference not set to an instance of an object error
**Describe the bug**
"Object reference not set to an instance of an object error" message has been occurring all of 2025, on multiple versions

**To Reproduce**
Anytime after playing a game, or when booting up Playnite for the first time

**Expected behavior**
The message to not occur

**Screenshots**

Image

**Extensions log**
[SuccessStory_2025-12-29.zip](https://github.com/user-attachments/files/24362304/SuccessStory_2025-12-29.zip)

### LINKED ISSUE #671: Epic Games connection still broken after 3.7 update
**Describe the bug**
The 3.7 update changelog mentions improved stability for the Epic Games connection, but I still can’t authenticate my Epic account at all. When I try to add Epic Games achievements via “Refresh data”, it throws` Object reference not set to an instance of an object`, and on top of that I now also get `Epic: user is not authenticate`. 

Trying to add achievements through Exophase isn’t any better either. Playnite just freezes completely and has to be force closed via Task Manager.

**To Reproduce**

1. Try to add Epic Games achievements via “Refresh data”.
2. Observe the errors `Object reference not set to an instance of an object` and `Epic: user is not authenticate`.
3. Try adding achievements via Exophase instead.
4. Playnite freezes and needs to be force-closed via Task Manager.

**Expected behavior**
Epic Games authentication works correctly and achievements can be added without errors or freezing Playnite.

**Screenshots**

Image

**Extensions log**

[extensions.log](https://github.com/user-attachments/files/24386793/extensions.log)

Another log when booting up Playnite for the first time after a system restart/Playnite restart/system shutdown: 

[extensions.log](https://github.com/user-attachments/files/24400027/extensions.log)

#666

### LINKED ISSUE #672: ShadPS4 issue
SuccessStory with the fix from matthew-pye loads the trophy list from shadPS4 game_data, but the issue is that newer versions of the emulator use a 10-digit Unix numeric format for timestamps, whereas previously a 17-digit numeric format was used. Because of this, all trophies appear as locked in Playnite itself, and in the SuccessStory .json file for the game, the trophy unlock date is "DateUnlocked": "0001-01-01T03:29:27.352+03:00".

### LINKED ISSUE #674: Cannot configurate Gamejolt
Image

[SuccessStory_2026-01-04.zip](https://github.com/user-attachments/files/24423373/SuccessStory_2026-01-04.zip)

### PR DESCRIPTION
**Pull request by Wibias**
This PR addresses multiple critical stability issues, including crashes during item updates, authentication loops in Epic/Exophase, invalid DateTime parsing in RPCS3/GameJolt/shadPS4, and compilation errors due to dependency mismatches. It also improves error logging and data persistence. Most of them are done in https://github.com/Lacro59/playnite-plugincommon/pull/170

Fixes #609
Fixes #661
Fixes #663
Fixes #664
Fixes #665
Fixes #666 
Fixes #667
Fixes #668 
Fixes #670 
Fixes #671 
Fixes #672 
Fixes #674 

### 1. Application Stability & Crashes
*   **ItemCollection.cs**: 
    *   Replaced a crashing `throw new Exception` with logging when attempting to update items that don't exist in the database.
    *   **Refinement**: Upgrade the log level from `Warn` to `Error` to ensure data integrity issues are visible in logs without crashing the plugin.
*   **GogAccountClient.cs**: Wrapped WebView operations in `try-catch(ObjectDisposedException)` to prevent crashes if the authentication window is closed prematurely during data fetch.

### 2. Epic Games Integration Fixes
*   **Null Safety**: Added null checks in `GetAssets`, `GetCatalogItem`, and `GetAchievementsSchema` to prevent `NullReferenceException` when the API returns incomplete data or fails.
*   **Authentication**: Fixed issues where users in "Public" mode suffered from missing tokens. The plugin now attempts to load stored tokens even if `UseAuth` is false.
*   **User Feedback**: Added a notification message in `GetAssets` to explicitly inform users when they need to temporarily enable Private mode to refresh their token.

### 3. Client-Specific Fixes
*   **shadPS4**: Fixed an issue where trophies showed unlock dates as "0001-01-01". The plugin now correctly identifies and detects 10-digit Unix timestamps (seconds) used by newer emulator versions while maintaining support for the legacy 17-digit format.
*   **EA**: Fixed `NullReferenceException` in `EaApi.cs` by adding a null check for `HeroImage`.
*   **GameJolt**: Fixed a crash caused by a typo in a fallback `DateTime` constructor (Month 15 corrected to Month 12).
*   **RPCS3**:
    *   Fixed crash due to invalid `DateTime` constructor usage.
    *   Fixed timestamp display issues by correctly specifying `DateTimeKind.Utc` when parsing achievement ticks.
*   **Exophase**:
    *   Resolved UI freeze during import by ensuring data fetching runs in a background thread/safe helper.
    *   Fixed a login loop by adding a short delay to allow cookies to flush to disk before reading.
*   **Humble Bundle**: Downgraded `AngleSharp` usage in `HumbleAccountClient.cs` (to `AngleSharp.Parser.Html`) to resolve compilation errors caused by version mismatch (project uses AngleSharp 0.9.9).

### 4. General Improvements
*   **Sorting**: Fixed a bug in `GameAchievements.cs` where sorting preferences were reset to default due to a side-effect in a property getter.
*   **Persistence**: Implemented `PluginDatabase.AddOrUpdate` across generic clients to ensure achievement data is saved immediately after fetching.

## Summary by CodeRabbit

* **New Features**
  * Achievements now auto-save after retrieval; added multi-source artwork fetching with in-memory + disk caching, background fetch, fuzzy image matching and a shared image resolver. Added async search, image extraction and estimate-time lookups.

* **Bug Fixes**
  * Reduced silent failures by expanding error logging, adding targeted try/catch, improved timeouts/retries, timestamp normalization and safer path validation.

* **Improvements**
  * UI sort/order sync, safer settings persistence, lifecycle/cleanup, concurrency controls and runtime timing instrumentation.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

**Comment by StarryByter** [comment]
@enkama Awesome job! Thank you so much for your work. I was having some issues with the Achievement Sync hanging and crashing for Xbox PC games and straight up not working when it comes to importing/resyncing Achievements for the EA App, recently, and your preliminary version 3.7.1 that I got from https://github.com/enkama/playnite-successstory-plugin/releases/tag/3.7.1 solved everything and is working flawlessly.

File: source/Clients/EpicAchievements.cs [hunk 1]
```diff
@@ -58,17 +71,115 @@ public override GameAchievements GetAchievements(Game game)
                     }
                     else
                     {
-                        if (!EpicApi.IsUserLoggedIn)
+                        // No achievements returned by Epic API — try Exophase as a fallback to obtain achievement metadata/images
```
Comment (Lacro59) [inline source/Clients/EpicAchievements.cs]: @enkama 
Why add Exophase achievements?
They will be present but not linked and not editable without indicating manual management.
